# Generated by Django 5.2.6 on 2025-11-12 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLTrainingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_processed_id', models.BigIntegerField(blank=True, null=True)),
                ('last_processed_datetime', models.DateTimeField(blank=True, null=True)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('kmeans_path', models.CharField(blank=True, max_length=255, null=True)),
                ('delay_path', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud_inicio', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('longitud_inicio', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('latitud_fin', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('longitud_fin', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('polyline_google', models.TextField(blank=True, null=True)),
                ('polyline_algo', models.TextField(blank=True, null=True)),
                ('distancia_google_m', models.FloatField(blank=True, null=True)),
                ('duracion_google_min', models.FloatField(blank=True, null=True)),
                ('distancia_algo_m', models.FloatField(blank=True, null=True)),
                ('duracion_algo_min', models.FloatField(blank=True, null=True)),
                ('retraso_estimado', models.FloatField(blank=True, help_text='Minutos: algoritmo - google', null=True)),
                ('envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envios.envio')),
                ('mensajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
