# Generated by Django 6.0.3 on 2026-06-07 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0005_envio_eta_min_envio_numero_seguimiento_and_more'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='duracion_estimada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='duracion_real',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='zona_asignada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RutaParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('eta_min', models.FloatField(blank=True, null=True)),
                ('distancia_desde_anterior_m', models.FloatField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas_ruta', to='envios.envio')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='rutas.ruta')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('ruta', 'envio')},
            },
        ),
    ]
