# Generated by Codex on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zonas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zona",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
