# Generated by Django 5.2.6 on 2025-11-12 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Recojo', 'Recojo'), ('Envío', 'Envío')], default='Envío', max_length=15)),
                ('remitente_nombre', models.CharField(max_length=150)),
                ('remitente_telefono', models.CharField(max_length=20)),
                ('destinatario_nombre', models.CharField(max_length=150)),
                ('destinatario_telefono', models.CharField(max_length=20)),
                ('origen_direccion', models.TextField()),
                ('destino_direccion', models.TextField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_servicio', models.CharField(choices=[('Estándar', 'Estándar'), ('Express', 'Express')], max_length=15)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Ruta', 'En Ruta'), ('Entregado', 'Entregado'), ('Rechazado', 'Rechazado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ruta_id', models.IntegerField(blank=True, null=True)),
                ('latitud_origen', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('longitud_origen', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('latitud_destino', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('longitud_destino', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('monto_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_pago', models.CharField(choices=[('Origen', 'Origen'), ('Destino', 'Destino')], max_length=15)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('mensajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajero', to='usuarios.usuario')),
                ('remitente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remitente', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Entregado', 'Entregado'), ('Rechazado', 'Rechazado')], max_length=15)),
                ('firma', models.ImageField(blank=True, null=True, storage='utils.storage.PrivateEncryptedStorage', upload_to='entregas/')),
                ('pagado', models.BooleanField(default=False)),
                ('mensajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.envio')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('Creado', 'Creado'), ('Asignado', 'Asignado'), ('Recogido', 'Recogido'), ('Entregado', 'Entregado'), ('Incidente', 'Incidente'), ('Cancelado', 'Cancelado')], max_length=20)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('ubicacion_latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ubicacion_longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.envio')),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Retraso', 'Retraso'), ('Daño', 'Daño'), ('Pérdida', 'Pérdida'), ('Otro', 'Otro')], max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Resuelto', 'Resuelto')], default='Pendiente', max_length=15, null=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.envio')),
            ],
        ),
    ]
