# Generated by Django 5.2.6 on 2025-11-12 03:36

import utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='firma',
            field=models.ImageField(blank=True, null=True, storage=utils.storage.PrivateEncryptedStorage(), upload_to='entregas/'),
        ),
    ]
