# Generated by Django 6.0.3 on 2026-06-06 15:42

import utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_alter_entrega_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=utils.storage.PrivateEncryptedStorage(), upload_to='entregas/'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialenvio',
            name='tipo_evento',
            field=models.CharField(choices=[('Actualizado', 'Actualizado'), ('Creado', 'Creado'), ('Asignado', 'Asignado'), ('Recogido', 'Recogido'), ('Entregado', 'Entregado'), ('Incidente', 'Incidente'), ('Cancelado', 'Cancelado')], max_length=20),
        ),
    ]
