# Generated by Django 6.0.3 on 2026-06-06 15:56

import utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_entrega_foto_entrega_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=utils.storage.PrivateEncryptedStorage(), upload_to='incidentes/'),
        ),
    ]
