# Generated by Django 6.0.3 on 2026-06-07 23:08

import django.db.models.deletion
import envios.models
from django.db import migrations, models


def poblar_numeros_seguimiento(apps, schema_editor):
    Envio = apps.get_model('envios', 'Envio')
    for envio in Envio.objects.filter(numero_seguimiento__isnull=True):
        envio.numero_seguimiento = f"CBE-{envio.pk:010d}"
        envio.save(update_fields=["numero_seguimiento"])


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_incidente_foto'),
        ('usuarios', '0002_passwordresettoken'),
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='eta_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='numero_seguimiento',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True),
        ),
        migrations.RunPython(poblar_numeros_seguimiento, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='envio',
            name='numero_seguimiento',
            field=models.CharField(db_index=True, default=envios.models.generar_numero_seguimiento, max_length=24, unique=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='orden_ruta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='zonas.zona'),
        ),
        migrations.AddField(
            model_name='historialenvio',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialenvio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_envio', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Ruta', 'En Ruta'), ('Entregado', 'Entregado'), ('Rechazado', 'Rechazado'), ('Fallido', 'Fallido'), ('Reintentado', 'Reintentado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='envio',
            name='tipo_pago',
            field=models.CharField(choices=[('Origen', 'Origen'), ('Destino', 'Destino'), ('Pendiente', 'Pendiente')], max_length=15),
        ),
        migrations.AlterField(
            model_name='historialenvio',
            name='tipo_evento',
            field=models.CharField(choices=[('Actualizado', 'Actualizado'), ('Creado', 'Creado'), ('Asignado', 'Asignado'), ('Recogido', 'Recogido'), ('Entregado', 'Entregado'), ('Incidente', 'Incidente'), ('Reasignado', 'Reasignado'), ('Notificado', 'Notificado'), ('Cancelado', 'Cancelado')], max_length=20),
        ),
        migrations.CreateModel(
            name='NotificacionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=180)),
                ('canal', models.CharField(choices=[('email', 'Correo'), ('push', 'Push'), ('sms', 'SMS'), ('sistema', 'Sistema')], default='sistema', max_length=20)),
                ('asunto', models.CharField(max_length=180)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='envios.envio')),
            ],
        ),
        migrations.CreateModel(
            name='ReasignacionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasignaciones', to='envios.envio')),
                ('mensajero_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasignaciones_salientes', to='usuarios.usuario')),
                ('mensajero_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones_entrantes', to='usuarios.usuario')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasignaciones_realizadas', to='usuarios.usuario')),
            ],
        ),
    ]
