# Generated by Django 5.2.6 on 2025-11-12 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionMensajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('mensajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilMensajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_mensajero', to='usuarios.usuario')),
            ],
        ),
    ]
