# Generated by Codex on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_empresa_perfilmensajero_disponible_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilmensajero",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="mensajeros/"),
        ),
    ]
