# Generated by Django 6.0.3 on 2026-06-07 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
        ('usuarios', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to='usuarios.usuario'),
        ),
    ]
